### RANDOM REWARDS CONFIG.YML ###
# To find help, please read the wiki
# https://github.com/viktorstrate/RandomRewards/wiki/Config

# The rewards the player should be able to get.
rewards:
  - 276 1 sharpness 2 unbreaking 1
  - 310
  - 322 1 1
  - 320 3
  
# The price it costs every time the player right-clicks the reward block
price:
  - 266 6
# The block the player has to right-click to trigger the
# Default is black wool
rewardBlock: 35 1 15
# Should the plugin use the permission randomrewards.user
# If false the player don't need the permission to get random rewards
usePermission: false