### RANDOM REWARDS CONFIG.YML ###
# To find help, please read the wiki
# https://github.com/viktorstrate/RandomRewards/wiki/Config

# The rewards the player should be able to get.
rewards:
  - 10
  - 33
  - ss22
  
# The price it costs every time the player right-clicks the reward block
price:
  items:
    GOLD_INGOT:
      amount: 3
      data: 0
# The block the player has to right-click to trigger the 
rewardBlock:
  WOOL:
      data: 2
# Should the plugin use the permission randomrewards.user
# If false the player don't need the permission to get random rewards
usePermission: false