rewards:
  items:
    DIAMOND_SWORD:
      amount: 1
      data: 0
    DIAMOND_HELMET:
      amount: 1
      data: 0
    WOOL:
      data: 2
      amount: 1
price:
  items:
    GOLD_INGOT:
      amount: 3